### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by shsagnik** [LHRLAB/Text2NKG#2]
1. How do we populate a graph DB with the processed training data or the test predictions. Do you have a script for that
2. Is it possible to infer the model over raw text, or is it necessary to convert it into the training format, any code snippet to inference will be nice as well

Thanks again for this great project and making the code public

**Comment by shsagnik** [comment]
I believe that is not what I asked 😅

**Comment by LHRLAB** [comment]
Okay, let me try to answer your question again. We are currently just extracting n-ary relational facts. If you want to save to graph DB, you need to design the schema of NKG. You can refer to Wikidata. For the second question, our model focuses the relation extraction done after NER. For raw data, you can use NER first, to get the entities and process them into our training format for training and testing.
